### PR TITLE
Added support for markdown and message display

### PR DESCRIPTION
**Pull request by halindrome**
With -m option will interpret subtest names as markdown
With -f option will also display failure text if any is supplied.

### CODE REVIEW

**Comment by halindrome** [comment]
Sample output at http://testdev.spec-ops.io/test-results/annotation-model/all.html

**Comment by sideshowbarker** [comment]
LGTM

Tested in my environment and works as expected

Would be good to have @darobin take a look at it if he’s able

**Comment by sideshowbarker** [comment]
The patches in this PR seem to have included a change that unnecessarily re-indented the entire `index.js` file and also made other other unnecessary whitespace/formatting changes that caused merge conflicts for PR #10.

So I went ahead and merged (and force-pushed) PR #10 instead, given that it was a clean patch that did not include unnecessary global indenting and whitespace/formatting changes.

That had the effect of reverting this PR. So the patch in PR now needs to be rebased against current master and re-submitted as a new PR—this time preferably without the unnecessary global indenting changes and other unnecessary whitespace/formatting changes.

I spent literally a couple hours try to get this unwound and rebased myself but unfortunately the unnecessary global indenting and other whitespace/formatting changes made it very difficult to figure out what actual substantive code changes this PR was making against the `index.js` source.

**Comment by halindrome** [comment]
I'm so sorry.  I will redo it.

**Comment by sideshowbarker** [comment]
> I'm so sorry.  I will redo it.

Nah, my fault for not catching it when I did the review. Sorry, but I have only been around a very limited amount of time recently. I should be back to normal hours after this week

**Pull request merged**
